server:
  port: 9999
  tomcat.threads.max: 0
  tomcat.uri-encoding: UTF-8
  shutdown: graceful

info.app.name: uno-card-game
info.env.name: local

management.endpoint.health.probes.enabled: true
management.endpoints.web.base-path: /
management.endpoints.web.exposure.include: refresh,health
endpoints.metrics.filter.gaugeSubmissions: PER_HTTP_METHOD
endpoints.metrics.filter.counterSubmissions: PER_HTTP_METHOD


#数据库配置
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/example?autoReconnect=true&autoReconnectForPools=true&serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&generateSimpleParameterMetadata=true&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=GMT%2b8
spring.datasource.username: pig
spring.datasource.password: 123456
spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.type: com.zaxxer.hikari.HikariDataSource
spring.datasource.hikari.minimum-idle: 5
spring.datasource.hikari.maximum-pool-size: 15
spring.datasource.hikari.auto-commit: true
spring.datasource.hikari.idle-timeout: 30000
spring.datasource.hikari.pool-name: DatebookHikariCP
spring.datasource.hikari.max-lifetime: 1800000
spring.datasource.hikari.connection-timeout: 30000
spring.datasource.hikari.connection-test-query: SELECT 1


#JPA配置
spring.jpa.database: mysql
spring.jpa.show-sql: false
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddlAuto: update
spring.jpa.open-in-view: false


#redis配置
spring.data.redis.host: localhost
spring.data.redis.port: 6379
#连接超时时间（毫秒）
spring.data.redis.timeout: 5000
#连接池最大连接数（使用负值表示没有限制）
spring.data.redis.lettuce.pool.max-active: 8
#连接池中的最大空闲连接
spring.data.redis.lettuce.pool.max-idle: 5
#连接池中的最小空闲连接
spring.data.redis.lettuce.pool.min-idle: 1
#连接池最大阻塞等待时间（使用负值表示没有限制）
spring.data.redis.lettuce.pool.max-wait: 5000


spring.data.redis.exchange-servers[0].mode: standalone
spring.data.redis.exchange-servers[0].standalone-node: localhost:6379
spring.data.redis.exchange-servers[0].database: 0
spring.data.redis.exchange-servers[0].max-total: 300
spring.data.redis.exchange-servers[0].min-idle: 50
spring.data.redis.exchange-servers[0].max-idle: 5
spring.data.redis.exchange-servers[0].timeout: 5000
spring.data.redis.exchange-servers[0].max-wait-millis: 5000


http.client.name: HTTPClient
http.client.connect-timeout: 100
http.client.read-timeout: 5000
http.client.write-timeout: 5000
http.client.max-idle-connections: 5
http.client.keep-alive-duration: 3000
http.client.thread-pool-size: 100
http.client.thread-alive-second: 60
http.client.max-requests: 200
http.client.max-requests-per-host: 100


#capacity: 令牌桶容量
#rate: 令牌桶每秒填充平均速率
bucket.capacity: 5000
bucket.rate: 100

logging:
  level:
    com.github.lansheng228: INFO


management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: refresh,health
